# -*- coding: utf-8 -*-
"""G14-BT Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wl5C2K3SrsvDsvJSwB0mwQPcUgKVvSbn

Install & Imports
"""

!pip install kagglehub opencv-python -q

import os
import cv2
import random
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import kagglehub

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB2
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

print("TensorFlow Version:", tf.__version__)

tf.keras.mixed_precision.set_global_policy("mixed_float16")

"""Download Dataset

"""

print("Downloading Dataset...")
path = kagglehub.dataset_download("darshandalvi12/brain-tumor-dataset")
print("Dataset Path:", path)

IMG_SIZE = 260
BATCH_SIZE = 16
EPOCHS_STAGE1 = 10
EPOCHS_STAGE2 = 15

CLASSES = ['glioma_tumor', 'meningioma_tumor', 'no_tumor', 'pituitary_tumor']

"""Load File Paths & splitting"""

def load_file_paths(base_path):
    image_paths, labels = [], []

    for root, _, files in os.walk(base_path):
        for file in files:
            if file.lower().endswith(('.jpg','.jpeg','.png')):
                folder = os.path.basename(root).lower()
                label = None

                if 'glioma' in folder: label = 0
                elif 'meningioma' in folder: label = 1
                elif 'no' in folder or 'normal' in folder: label = 2
                elif 'pituitary' in folder: label = 3

                if label is not None:
                    image_paths.append(os.path.join(root,file))
                    labels.append(label)

    return np.array(image_paths), np.array(labels)

file_paths, targets = load_file_paths(path)

X_train, X_test, y_train, y_test = train_test_split(
    file_paths, targets, test_size=0.2, stratify=targets, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(
    X_test, y_test, test_size=0.5, stratify=y_test, random_state=42)

print("Dataset Ready ✅")

import matplotlib.pyplot as plt
import numpy as np

# Class names
class_names = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']

# Count samples
class_counts = np.bincount(targets)

# Professional color palette
colors = ['#4C72B0', '#55A868', '#C44E52', '#8172B2']

plt.figure(figsize=(9,5))

bars = plt.bar(class_names, class_counts, color=colors)

plt.title("Dataset Class Distribution", fontsize=14, fontweight='bold')
plt.xlabel("Tumor Type", fontsize=12)
plt.ylabel("Number of Images", fontsize=12)

plt.grid(axis='y', linestyle='--', alpha=0.6)

# Add value labels on top
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 5,
        str(int(height)),
        ha='center',
        fontsize=11,
        fontweight='bold'
    )

plt.tight_layout()
plt.show()

"""Advanced Medical Preprocessing"""

def advanced_preprocess_cv2(image_np):

    if image_np.dtype != np.uint8:
        if image_np.max() <= 1.0:
            image_np = (image_np * 255).astype(np.uint8)
        else:
            image_np = image_np.astype(np.uint8)

    gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)
    gray = cv2.medianBlur(gray, 3)

    blurred = cv2.GaussianBlur(gray, (5,5), 0)
    _, thresh = cv2.threshold(blurred, 45, 255, cv2.THRESH_BINARY)
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=2)

    contours, _ = cv2.findContours(
        thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if len(contours) == 0:
        return image_np

    c = max(contours, key=cv2.contourArea)

    mask = np.zeros(gray.shape, dtype=np.uint8)
    cv2.drawContours(mask, [c], -1, 255, -1)
    masked = cv2.bitwise_and(gray, gray, mask=mask)

    x, y, w, h = cv2.boundingRect(c)
    cropped = masked[y:y+h, x:x+w]

    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    enhanced = clahe.apply(cropped)

    final_rgb = cv2.cvtColor(enhanced, cv2.COLOR_GRAY2RGB)

    return final_rgb

"""TensorFlow Wrapper (Z-score Included)"""

def preprocess_image(path):

    path = path.decode("utf-8")

    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = advanced_preprocess_cv2(img)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img.astype(np.float32)

    mean = np.mean(img)
    std = np.std(img) + 1e-7
    img = (img - mean) / std

    return img


def preprocess_image_tf(path, label):

    img = tf.numpy_function(
        preprocess_image,
        [path],
        tf.float32
    )

    img.set_shape((IMG_SIZE, IMG_SIZE, 3))

    return img, label

"""Visualization Suite"""

print("\n--- Visualization: Advanced Medical Preprocessing ---")

def show_comparison():

    rand_idx = random.randint(0, len(file_paths)-1)
    img_path = file_paths[rand_idx]

    original = cv2.imread(img_path)
    original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)

    intermediate = advanced_preprocess_cv2(original)

    processed = preprocess_image(img_path.encode())

    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(original)
    plt.title("1. Original Raw Scan")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(intermediate)
    plt.title("2. Masked + CLAHE")
    plt.axis("off")

    plt.subplot(1,3,3)
    vis = (processed - processed.min()) / (processed.max()-processed.min()+1e-7)
    plt.imshow(vis)
    plt.title("3. Z-score Normalized")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

show_comparison()

"""Data Pipeline"""

train_ds = (
    tf.data.Dataset.from_tensor_slices((X_train, y_train))
    .shuffle(1000)
    .map(preprocess_image_tf, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

val_ds = (
    tf.data.Dataset.from_tensor_slices((X_val, y_val))
    .map(preprocess_image_tf, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

test_ds = (
    tf.data.Dataset.from_tensor_slices((X_test, y_test))
    .map(preprocess_image_tf)
    .batch(BATCH_SIZE)
)

"""Class Weights"""

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(class_weights))
print("Class Weights:", class_weights)

"""Build EfficientNetB2"""

base_model = EfficientNetB2(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False

inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(512, activation="relu")(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(4, activation="softmax", dtype="float32")(x)

model = models.Model(inputs, outputs)

model.compile(
    optimizer=Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

"""Training + Fine Tuning"""

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3),
    ModelCheckpoint("best_model.keras", save_best_only=True)
]
model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_STAGE1,
    class_weight=class_weights,
    callbacks=callbacks
)
base_model.trainable = True
for layer in base_model.layers[:-40]:
    layer.trainable = False

model.compile(
    optimizer=Adam(1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)
model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_STAGE2,
    class_weight=class_weights,
    callbacks=callbacks
)

"""Evaluation"""

from google.colab import drive
drive.mount('/content/drive')

model.save('/content/drive/MyDrive/my_model.keras')

test_loss, test_acc = model.evaluate(test_ds)
print(f"\nFinal Test Accuracy: {test_acc*100:.2f}%")

model.save("brain_tumor_model.keras")
from google.colab import drive
drive.mount('/content/drive')

model.save('/content/drive/MyDrive/my_model.keras')

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

# Collect predictions
y_true = []
y_pred = []

for images, labels in test_ds:
    preds = model.predict(images)
    y_true.extend(labels.numpy())
    y_pred.extend(preds)

y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Binarize labels for multi-class ROC
n_classes = 4
y_true_bin = label_binarize(y_true, classes=[0,1,2,3])

# Compute ROC for each class
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot ROC curves
plt.figure(figsize=(8,6))

class_names = ['Glioma','Meningioma','No Tumor','Pituitary']

for i in range(n_classes):
    plt.plot(fpr[i], tpr[i],
             label=f'{class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0,1],[0,1],'k--')  # Random classifier line
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve for Brain Tumor Classification")
plt.legend()
plt.grid()
plt.show()



"""Upload Prediction"""

from google.colab import files
import matplotlib.pyplot as plt
import cv2
import numpy as np
from tensorflow.keras.models import load_model

model = load_model('/content/drive/MyDrive/my_model.keras')

def predict_uploaded_image(model, model_accuracy):

    uploaded = files.upload()

    for filename in uploaded.keys():

        # Read image
        img_bgr = cv2.imread(filename)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        # 🔥 Display original image
        plt.figure()
        plt.imshow(img_rgb)
        plt.axis("off")
        plt.title("Uploaded MRI Image")
        plt.show()

        # Advanced preprocessing
        img = advanced_preprocess_cv2(img_rgb)
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype(np.float32)

        # Z-score normalization
        mean = np.mean(img)
        std = np.std(img) + 1e-7
        img = (img - mean) / std

        # Add batch dimension
        img = np.expand_dims(img, axis=0)

        # Prediction
        predictions = model.predict(img, verbose=0)
        predicted_index = np.argmax(predictions[0])
        predicted_label = CLASSES[predicted_index]
        confidence = float(np.max(predictions[0])) * 100

        print("\n==============================")

        if predicted_label == "no_tumor":
            print("🟢 Brain Tumor: NEGATIVE")
        else:
            print("🔴 Brain Tumor: POSITIVE")
            print(f"Type: {predicted_label.upper()}")

        print(f"Confidence: {confidence:.2f}%")
        print(f"Model Accuracy: {model_accuracy*100:.2f}%")
        print("==============================\n")
predict_uploaded_image(model, test_acc)

model = load_model('/content/drive/MyDrive/my_model.keras')
